### ISSUE TITLE
Community Auditor: IAM Policy permits * resources when actions support resource constraints

### ISSUE THREAD

**Issue by kmcquade** [duo-labs/parliament#72]
I will add this when #66 is merged.  

Basically, it would be very useful to flag when IAM policies grant access to * resources. This is not necessary in some cases, since some IAM Actions do not support resource constraints (restricting to ARNs). But this check would identify when IAM Actions that DO support resource constraints are set to `*` resources.

I'd mark it as an INFO level finding, since that doesn't necessarily constitute a security issue or violation of least privilege (more often than not, it does, but we wouldn't want to assume).

**Comment by 0xdabbad00** [comment]
This would best be done by creating a finding at this location: https://github.com/duo-labs/parliament/blob/01b20a57f66b537189e3e3a86c05db70ca9d59b2/parliament/statement.py#L836

I originally avoided creating findings for this because it would be be overwhelming for many environments, but it would be good to let users decide whether or not they want these.

**Comment by kmcquade** [comment]
oh sweet
